### ISSUE TITLE
For some reason the release version of KthuraEdit.exe refuses to launch

### ISSUE THREAD

**Issue by Tricky1975** [TrickyGameTools/Kthura#45]
This is VERY VERY hard to debug, so please hang on with me...

**Comment by Tricky1975** [comment]
Report by .NET
~~~
See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.NullReferenceException: Object reference not set to an instance of an object.
   at MonoGame.Framework.WinFormsGameWindow.OnDeactivate(Object sender, EventArgs eventArgs)
   at System.Windows.Forms.Form.OnDeactivate(EventArgs e)
   at System.Windows.Forms.Form.set_Active(Boolean value)
   at System.Windows.Forms.Form.WmActivate(Message& m)
   at System.Windows.Forms.Form.WndProc(Message& m)
   at Microsoft.Xna.Framework.Windows.WinFormsGameForm.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)


************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3324.0 built by: NET472REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework/v4.0.30319/mscorlib.dll
----------------------------------------
KthuraEdit
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///E:/Projects/Applications/VisualStudio/Kthura/source/KthuraEdit/bin/Windows/x86/Release/KthuraEdit.exe
----------------------------------------
MonoGame.Framework
    Assembly Version: 3.7.1.189
    Win32 Version: 3.7.1.189
    CodeBase: file:///E:/Projects/Applications/VisualStudio/Kthura/source/KthuraEdit/bin/Windows/x86/Release/MonoGame.Framework.DLL
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3190.0 built by: NET472REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3353.0 built by: NET472REL1LAST_B
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3324.0 built by: NET472REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3324.0 built by: NET472REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3324.0 built by: NET472REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3190.0 built by: NET472REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
SharpDX
    Assembly Version: 4.0.1.0
    Win32 Version: 4.0.1
    CodeBase: file:///E:/Projects/Applications/VisualStudio/Kthura/source/KthuraEdit/bin/Windows/x86/Release/SharpDX.DLL
----------------------------------------
SharpDX.XAudio2
    Assembly Version: 4.0.1.0
    Win32 Version: 4.0.1
    CodeBase: file:///E:/Projects/Applications/VisualStudio/Kthura/source/KthuraEdit/bin/Windows/x86/Release/SharpDX.XAudio2.DLL
----------------------------------------
NLua
    Assembly Version: 1.4.14.0
    Win32 Version: 1.4.14.0
    CodeBase: file:///E:/Projects/Applications/VisualStudio/Kthura/source/KthuraEdit/bin/Windows/x86/Release/NLua.DLL
----------------------------------------
KeraLua
    Assembly Version: 1.0.7.0
    Win32 Version: 1.0.7.0
    CodeBase: file:///E:/Projects/Applications/VisualStudio/Kthura/source/KthuraEdit/bin/Windows/x86/Release/KeraLua.DLL
----------------------------------------
SharpDX.DXGI
    Assembly Version: 4.0.1.0
    Win32 Version: 4.0.1
    CodeBase: file:///E:/Projects/Applications/VisualStudio/Kthura/source/KthuraEdit/bin/Windows/x86/Release/SharpDX.DXGI.DLL
----------------------------------------
System.Runtime
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3190.0
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Runtime/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Runtime.dll
----------------------------------------
SharpDX.Direct3D11
    Assembly Version: 4.0.1.0
    Win32 Version: 4.0.1
    CodeBase: file:///E:/Projects/Applications/VisualStudio/Kthura/source/KthuraEdit/bin/Windows/x86/Release/SharpDX.Direct3D11.DLL
----------------------------------------

************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.


~~~
